export const FETCH_SOURCES_SUCCEEDED = 'FETCH_SOURCES_SUCCEEDED';
export const FETCH_SOURCES_FAILED = 'FETCH_SOURCES_FAILED';

export const FETCH_SOURCE_SUCCEEDED = 'FETCH_SOURCE_SUCCEEDED';
export const FETCH_SOURCE_FAILED = 'FETCH_SOURCE_FAILED';

export const FETCH_MESSAGES_FOR_SOURCE_SUCCEEDED =
  'FETCH_MESSAGES_FOR_SOURCE_SUCCEEDED';
export const FETCH_MESSAGES_FOR_SOURCE_FAILED =
  'FETCH_MESSAGES_FOR_SOURCE_FAILED';

export const FETCH_MESSAGE_STATUS_COUNTS_FOR_SOURCE_SUCCEEDED =
  'FETCH_MESSAGE_STATUS_COUNTS_FOR_SOURCE_SUCCEEDED';
export const FETCH_MESSAGE_STATUS_COUNTS_FOR_SOURCE_FAILED =
  'FETCH_MESSAGE_STATUS_COUNTS_FOR_SOURCE_FAILED';

export const UPDATE_SOURCE_SUCCEEDED = 'UPDATE_SOURCE_SUCCEEDED';
export const UPDATE_SOURCE_FAILED = 'UPDATE_SOURCE_FAILED';
