export const FETCH_SOURCES_SUCCEEDED = 'FETCH_SOURCES_SUCCEEDED';
export const FETCH_SOURCES_FAILED = 'FETCH_SOURCES_FAILED';

export const FETCH_SOURCE_SUCCEEDED = 'FETCH_SOURCE_SUCCEEDED';
export const FETCH_SOURCE_FAILED = 'FETCH_SOURCE_FAILED';
